# Generated by Django 4.0.2 on 2022-02-04 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0004_alter_contracts_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mileages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('km', models.PositiveIntegerField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.contracts')),
            ],
        ),
    ]
