# Generated by Django 4.0.2 on 2022-02-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileages',
            name='km',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
