# Generated by Django 4.0.2 on 2022-02-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_alter_mileages_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileages',
            name='date',
            field=models.DateField(),
        ),
    ]
