# Generated by Django 4.0.2 on 2022-02-03 06:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicle_no', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=4)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('year_of_registration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2022)])),
                ('coe_expiry_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.users')),
            ],
        ),
    ]
