# Generated by Django 4.0.2 on 2022-02-03 07:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('ic_no', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[A-Z]\\d{7}[A-Z]')])),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('dob', models.DateField()),
                ('license_no', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(regex='^[A-Z]\\d{7}[A-Z]')])),
                ('expiry_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.users')),
            ],
        ),
    ]
