# Generated by Django 4.0.2 on 2022-02-04 05:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_licenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('contract_no', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[A-Z]\\d{9}')])),
                ('base_rate', models.PositiveIntegerField()),
                ('km_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField()),
                ('application_date', models.DateField(auto_now_add=True)),
                ('application_status', models.BooleanField(default=False)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='Payables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('outstanding', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.contracts')),
            ],
        ),
    ]
