# Generated by Django 4.0.2 on 2022-02-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_contracts_payables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
