# Generated by Django 4.0.2 on 2022-02-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_contracts_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracts',
            options={'ordering': ['application_date']},
        ),
    ]
